# This file is not secret
# It is OK to have in VCS
# Please do not open an issue
apiVersion: v1
kind: Config
clusters:
  - name: gke_pxlblue_us-central1-c_pxl-blue
    cluster:
      server: "https://104.198.141.41"
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLakNDQWhLZ0F3SUJBZ0lRV2c4VFFSTUNKeEF0SjFFdzFOWWM5VEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRNE5HVXhZVGRqWXkxaU16RmtMVFEwTVdFdE9HVm1ZaTFqTXpVM05URXhZalZrWldNdwpIaGNOTWpBd09URXpNakF3TlRBMVdoY05NalV3T1RFeU1qRXdOVEExV2pBdk1TMHdLd1lEVlFRREV5UTROR1V4CllUZGpZeTFpTXpGa0xUUTBNV0V0T0dWbVlpMWpNelUzTlRFeFlqVmtaV013Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNyaEhoNk9NZW92a0JpdkpLaFAyTXRxNTBJT09MWVo5K1RUT3R4QzYybAoweTlqN2RydkF0ZWdWaVFxMXVwcWM1cmF4Vi9kM1hmUTBuMFV1NlVXOG8rajh1MjNJN25BTENCMGNYK21hbm1ECmxrUWxPNy9DSlpFeW1PTEU3VWduL3Y0S3Uvdk8vS0IxVUFwcVcvNVdTSFhWdWVBZFZBUlliTUUrUnc2M015QksKc0VIRGJLR3FJaUtuY1dTTEpDYW9zaS8rY2JHc2JtR2pMbytad3k1bGF1OHdPZG0zUHhCTlQ1bnZ3ZzhXc2x5VgpROExCNjU1TDdLckZXam9zVjJTSTZIbUI4NFJRdWJjUVVHa2RMV3RsRjdYRXhzQTNuNk9LTjIrSUhwTUNLTU9zCkNKekZQNzVYRmc0cHhHNEVFczZxRG5oRi9UMUJ2NXRTRXU4OCtjWDVXQ1hIQWdNQkFBR2pRakJBTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUaXJpZmVITFJHME9rZQozeVV0S0FYb2hiQm5CekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBWVNvV09XeVRFUHFPaXQ4ZmRmdXNtbzFuCngvSnZ0WlJuKy9MUXAzREFQUjBBTGh4SDlLbThNRTFGQUJsYVlidTZpUnhBSTFwckxwbkJkbXFyTXl6blRPTi8KVmZyWFArRml0bkM1VklQZklKc3JDTFBZanljNmo4c3NRUDQvRTY1OTN1QzBIaUxsSzZpdVRwdzMxclVqSDNSVQpDUGRwdEhHbkRnazFpdGRUbmx0RXAyL0F2UDNDZVlxSmtvczhhc2VoTDByV0FpOU1pcWp6K2hrR05HTC9ydnFRCmo0ZFFRRGRiVGxiY3FPZmNGT0pHZnZKTzBoOTYwcDhoYmk2THNEMEZaZTVaelQ3MmVDTFVzdVZyUDJSZElJSlAKR0YzNHZhMVhQaG9MUDg0N21SdExpais4MDY1MXArWVVlb2hNaWFET21qZHc3U2lCVmlESHhJc3BWNnp4MWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
contexts:
  - context:
      cluster: gke_pxlblue_us-central1-c_pxl-blue
      namespace: production
      user: gke_pxlblue_us-central1-c_pxl-blue
    name: gke_pxlblue_us-central1-c_pxl-blue
current-context: gke_pxlblue_us-central1-c_pxl-blue
users:
  - name: gke_pxlblue_us-central1-c_pxl-blue
    user:
      auth-provider:
        name: gcp
